In [1]:
library(ggplot2)
library(dplyr)
library(gridExtra)

df_meta <- read.csv("../Data_Metadata_Annotation.csv")
dup_cols <- c("Technology", "Tissue", "Dataset", "Sample")
df_meta <- df_meta %>% mutate(
  is_duplicated = duplicated(select(., all_of(dup_cols)))
)
df_duplicates <- df_meta %>% filter(is_duplicated)
df_meta_unique <- df_meta %>% filter(!is_duplicated) %>% select(-is_duplicated)

df_meta <- df_meta_unique

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union



Attaching package: ‘gridExtra’


The following object is masked from ‘package:dplyr’:

    combine

In [3]:
df_meta

    X   Technology Tissue Dataset
1    0  10x Visium Brain  DLPFC
2    1  10x Visium Brain  DLPFC
3    2  10x Visium Brain  DLPFC
4    3  10x Visium Brain  DLPFC
5    4  10x Visium Brain  DLPFC
6    5  10x Visium Brain  DLPFC
7    6  10x Visium Brain  DLPFC
8    7  10x Visium Brain  DLPFC
9    8  10x Visium Brain  DLPFC
10   9  10x Visium Brain  DLPFC
11  10  10x Visium Brain  DLPFC
12  11  10x Visium Brain  DLPFC
13  12  10x Visium Brain  Mouse Brain
14  13  10x Visium Brain  Mouse Brain
15  14  10x Visium Brain  Mouse Brain
16  15  10x Visium Brain  Mouse Brain
17  16  10x Visium Brain  Mouse Brain
18  17  10x Visium Brain  Human Cerebellum
19  18  10x Visium Brain  Mouse Brain
20  19  10x Visium Brain  Mouse Brain
21  23  10x Visium Breast Human Breast Cancer
22  24  10x Visium Breast Human Breast Cancer
23  25  10x Visium Breast Human Breast Cancer
24  26  10x Visium Breast Human Breast
25  27  10x Visium Breast Human Breast
26  28  10x Visium Breast Human Breast
27  29  10x Visium Breast Human Breast
28  30  10x Visium Breast Human Breast
29  31  10x Visium Breast Human Breast
30  32  10x Visium Breast Human Breast
⋮   ⋮   ⋮          ⋮      ⋮
339 356 Slideseq   Kidney Mouse Normal
340 357 Slideseq   Kidney Mouse Normal
341 358 Slideseq   Kidney Mouse Normal
342 359 Slideseq   Kidney Mouse Normal
343 360 Slideseq   Kidney Mouse Normal
344 361 Slideseq   Kidney Mouse Normal
345 362 Slideseq   Kidney Mouse Normal
346 363 Slideseq   Kidney Mouse Normal
347 364 Slideseq   Kidney Mouse Normal
348 365 Slideseq   Kidney Mouse Normal
349 366 Slideseq   Kidney Mouse Diabetic Kidney Disease
350 367 Slideseq   Kidney Mouse Diabetic Kidney Disease
351 368 Slideseq   Kidney Mouse Diabetic Kidney Disease
352 369 Slideseq   Kidney Mouse Diabetic Kidney Disease
353 370 Slideseq   Kidney Mouse Diabetic Kidney Disease
354 371 Slideseq   Kidney Mouse Diabetic Kidney Disease
355 372 Slideseq   Kidney Mouse Diabetic Kidney Disease
356 373 Slideseq   Kidney Mouse Diabetic Kidney Disease
357 374 Slideseq   Kidney Mouse Diabetic Kidney Disease
358 375 Slideseq   Kidney Mouse Diabetic Kidney Disease
359 376 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
360 377 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
361 378 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
362 379 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
363 380 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
364 381 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
365 382 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
366 383 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
367 384 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
368 385 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
    Sample                      Number.of.Spots Number.of.Genes
1   151507                      4221            33538
2   151508                      4381            33538
3   151509                      4788            33538
4   151510                      4595            33538
5   151669                      3636            33538
6   151670                      3484            33538
7   151671                      4093            33538
8   151672                      3888            33538
9   151673                      3611            33538
10  151674                      3635            33538
11  151675                      3566            33538
12  151676                      3431            33538
13  FF3_S1_Sagittal_Posterior   3353            31053
14  FF4_S2_Sagittal_Anterior    2825            31053
15  FF5_S2_Sagittal_Posterior   3293            31053
16  FF6                         2560            31053
17  FF7                         2500            31053
18  Whole_Transcriptome         4992            36601
19  Section_Coronal             2686            32285
20  S1_Sagittal_Anterior_Level1 2693            32285
21  Block_A_Section1            3798            36601
22  Block_A_Section2            3987            36601
23  Whole_Transcriptome         4898            36601
24  sample01                    2103            36601
25  sample02                    1400            36601
26  sample03                    2364            36601
27  sample04                    2504            36601
28  sample05                    2224            36601
29  sample06                    3037            36601
30  sample07                    2086            36601
⋮   ⋮                           ⋮               ⋮
339 Puck_191109_07              21825           20550
340 Puck_191109_08              26486           19446
341 Puck_191109_09              25279           20262
342 Puck_191109_10              12465           19388
343 Puck_191112_02              17926           21286
344 Puck_191112_04              13096           20812
345 Puck_191112_05               9075           19621
346 Puck_191112_07              12675           19157
347 Puck_191112_13              14497           17669
348 Puck_191204_13              30477           22102
349 Puck_191109_14              10930           18956
350 Puck_191109_18              16582           18064
351 Puck_191109_19              16936           18447
352 Puck_191109_20              12038           17811
353 Puck_191112_08               6968           18662
354 Puck_191204_03              18868           21508
355 Puck_191204_04              20917           21855
356 Puck_191204_05              26388           21564
357 Puck_191204_07              29130           22121
358 Puck_191204_08              21518           21265
359 Puck_191223_21              21027           20803
360 Puck_191223_22              18459           21695
361 Puck_191223_23              23176           21431
362 Puck_191223_24              27116           21486
363 Puck_200102_09              24405           21651
364 Puck_200104_06              28902           21086
365 Puck_200104_07              28401           21263
366 Puck_200104_09              23887           21477
367 Puck_200104_10              24454           20322
368 Puck_200104_14              20613           20986
    Genes.Detected.per.Spot Sparsity  Avg.Expression.per.Spot
1   1409.482                0.958     0.077
2   1191.235                0.964     0.063
3   1434.161                0.957     0.076
4   1368.559                0.959     0.073
5   1796.764                0.946     0.112
6   1675.843                0.950     0.102
7   1859.503                0.945     0.116
8   1770.257                0.947     0.109
9   2207.998                0.934     0.137
10  2697.521                0.920     0.176
11  1807.521                0.946     0.107
12  1936.961                0.942     0.115
13  4541.987                0.854     0.549
14  5015.129                0.838     0.637
15  4385.757                0.859     0.506
16  4722.021                0.848     0.637
17  4389.446                0.859     0.584
18  2855.558                0.922     0.177
19  5953.154                0.816     0.988
20  5883.059                0.818     0.796
21  5621.993                0.846     0.596
22  5458.042                0.851     0.571
23  3522.717                0.904     0.280
24  2602.554                0.929     0.237
25  2337.706                0.936     0.268
26  1756.434                0.952     0.106
27  1490.822                0.959     0.088
28  2492.613                0.932     0.266
29  2348.268                0.936     0.198
30  1805.425                0.951     0.161
⋮   ⋮                       ⋮         ⋮
339 191.54515               0.9906791 0.012688714
340  84.37408               0.9956611 0.005523240
341 129.10008               0.9936285 0.008451241
342 121.45608               0.9937355 0.007990991
343 221.41459               0.9895981 0.016012911
344 187.32254               0.9909993 0.012451447
345  71.24364               0.9963690 0.005150831
346 109.90154               0.9942631 0.007933210
347  52.73801               0.9970152 0.003983201
348 270.73938               0.9877505 0.016941719
349 102.65343               0.9945846 0.008096117
350  61.87330               0.9965748 0.004977034
351  62.17932               0.9966293 0.004400163
352  58.60375               0.9967097 0.004765029
353  80.60706               0.9956807 0.005086290
354 349.74237               0.9837390 0.025502034
355 326.95788               0.9850397 0.022873504
356 293.68770               0.9863806 0.019791855
357 234.97055               0.9893779 0.015222518
358 193.42722               0.9909040 0.012158376
359 391.78499               0.9811669 0.029463859
360 436.45750               0.9798821 0.028967535
361 343.66422               0.9839642 0.023433484
362 306.32896               0.9857429 0.020359026
363 413.17959               0.9809164 0.026858885
364 296.76351               0.9859260 0.019267663
365 286.55248               0.9865234 0.019271897
366 390.69326               0.9818088 0.026945865
367 173.13654               0.9914803 0.010847545
368 352.71130               0.9831930 0.024484957
    Avg.Non.Zero.Expression.per.Spot Number.of.Clusters Annotation_Level
1   1.782                             7                 domain
2   1.723                             7                 domain
3   1.718                             7                 domain
4   1.735                             7                 domain
5   2.009                             5                 domain
6   1.965                             5                 domain
7   1.998                             5                 domain
8   1.975                             5                 domain
9   1.983                             7                 domain
10  2.094                             7                 domain
11  1.895                             7                 domain
12  1.922                             7                 domain
13  3.438                            17                 domain
14  3.770                            18                 domain
15  3.311                            18                 domain
16  3.933                            17                 domain
17  3.933                            17                 domain
18  2.069                             8                 domain
19  5.085                            15                 domain
20  4.141                             9                 domain
21  3.463                            20                 domain
22  3.463                            10                 domain
23  2.678                             9                 domain
24  2.548                             9                 domain
25  2.638                             9                 domain
26  1.932                             9                 domain
27  1.705                             9                 domain
28  3.025                             9                 domain
29  2.404                             9                 domain
30  2.387                             9                 domain
⋮   ⋮                                ⋮                  ⋮
339 1.291849                         14                 celltype
340 1.216153                         13                 celltype
341 1.252716                         14                 celltype
342 1.216045                         13                 celltype
343 1.396501                         14                 celltype
344 1.286999                          9                 celltype
345 1.304500                         12                 celltype
346 1.291995                         13                 celltype
347 1.231522                         11                 celltype
348 1.253705                         14                 celltype
349 1.428996                         12                 celltype
350 1.422188                         13                 celltype
351 1.241214                         13                 celltype
352 1.430274                         13                 celltype
353 1.130741                         12                 celltype
354 1.374383                         14                 celltype
355 1.360675                         14                 celltype
356 1.314982                         14                 celltype
357 1.300891                         14                 celltype
358 1.231232                         14                 celltype
359 1.407635                         14                 celltype
360 1.304167                         10                 celltype
361 1.308914                         14                 celltype
362 1.296865                         14                 celltype
363 1.262877                         10                 celltype
364 1.258529                         12                 celltype
365 1.297987                         12                 celltype
366 1.322177                         13                 celltype
367 1.191887                         13                 celltype
368 1.299718                         10                 celltype
    Original_Annotation                    Level
1   Manual Annotation                      Level 1
2   Manual Annotation                      Level 1
3   Manual Annotation                      Level 1
4   Manual Annotation                      Level 1
5   Manual Annotation                      Level 1
6   Manual Annotation                      Level 1
7   Manual Annotation                      Level 1
8   Manual Annotation                      Level 1
9   Manual Annotation                      Level 1
10  Manual Annotation                      Level 1
11  Manual Annotation                      Level 1
12  Manual Annotation                      Level 1
13  Unsupervised clustering                Level 3
14  Unsupervised clustering                Level 3
15  Unsupervised clustering                Level 3
16  Unsupervised clustering                Level 3
17  Unsupervised clustering                Level 3
18  Unsupervised clustering                Level 3
19  Manual Annotation                      Level 1
20  Manual Annotation                      Level 1
21  Manual Annotation                      Level 1
22  Unsupervised clustering                Level 3
23  Unsupervised clustering                Level 3
24  Unsupervised clustering + Marker genes Level 1
25  Unsupervised clustering + Marker genes Level 1
26  Unsupervised clustering + Marker genes Level 1
27  Unsupervised clustering + Marker genes Level 1
28  Unsupervised clustering + Marker genes Level 1
29  Unsupervised clustering + Marker genes Level 1
30  Unsupervised clustering + Marker genes Level 1
⋮   ⋮                                      ⋮
339 Supervised Transfer                    Level 2
340 Supervised Transfer                    Level 2
341 Supervised Transfer                    Level 2
342 Supervised Transfer                    Level 2
343 Supervised Transfer                    Level 2
344 Supervised Transfer                    Level 2
345 Supervised Transfer                    Level 2
346 Supervised Transfer                    Level 2
347 Supervised Transfer                    Level 2
348 Supervised Transfer                    Level 2
349 Supervised Transfer                    Level 2
350 Supervised Transfer                    Level 2
351 Supervised Transfer                    Level 2
352 Supervised Transfer                    Level 2
353 Supervised Transfer                    Level 2
354 Supervised Transfer                    Level 2
355 Supervised Transfer                    Level 2
356 Supervised Transfer                    Level 2
357 Supervised Transfer                    Level 2
358 Supervised Transfer                    Level 2
359 Supervised Transfer                    Level 2
360 Supervised Transfer                    Level 2
361 Supervised Transfer                    Level 2
362 Supervised Transfer                    Level 2
363 Supervised Transfer                    Level 2
364 Supervised Transfer                    Level 2
365 Supervised Transfer                    Level 2
366 Supervised Transfer                    Level 2
367 Supervised Transfer                    Level 2
368 Supervised Transfer                    Level 2

In [6]:
df_all

    X   Technology Tissue Dataset
1    0  10x Visium Brain  DLPFC
2    1  10x Visium Brain  DLPFC
3    2  10x Visium Brain  DLPFC
4    3  10x Visium Brain  DLPFC
5    4  10x Visium Brain  DLPFC
6    5  10x Visium Brain  DLPFC
7    6  10x Visium Brain  DLPFC
8    7  10x Visium Brain  DLPFC
9    8  10x Visium Brain  DLPFC
10   9  10x Visium Brain  DLPFC
11  10  10x Visium Brain  DLPFC
12  11  10x Visium Brain  DLPFC
13  12  10x Visium Brain  Mouse Brain
14  13  10x Visium Brain  Mouse Brain
15  14  10x Visium Brain  Mouse Brain
16  15  10x Visium Brain  Mouse Brain
17  16  10x Visium Brain  Mouse Brain
18  17  10x Visium Brain  Human Cerebellum
19  18  10x Visium Brain  Mouse Brain
20  19  10x Visium Brain  Mouse Brain
21  23  10x Visium Breast Human Breast Cancer
22  24  10x Visium Breast Human Breast Cancer
23  25  10x Visium Breast Human Breast Cancer
24  26  10x Visium Breast Human Breast
25  27  10x Visium Breast Human Breast
26  28  10x Visium Breast Human Breast
27  29  10x Visium Breast Human Breast
28  30  10x Visium Breast Human Breast
29  31  10x Visium Breast Human Breast
30  32  10x Visium Breast Human Breast
⋮   ⋮   ⋮          ⋮      ⋮
339 356 Slideseq   Kidney Mouse Normal
340 357 Slideseq   Kidney Mouse Normal
341 358 Slideseq   Kidney Mouse Normal
342 359 Slideseq   Kidney Mouse Normal
343 360 Slideseq   Kidney Mouse Normal
344 361 Slideseq   Kidney Mouse Normal
345 362 Slideseq   Kidney Mouse Normal
346 363 Slideseq   Kidney Mouse Normal
347 364 Slideseq   Kidney Mouse Normal
348 365 Slideseq   Kidney Mouse Normal
349 366 Slideseq   Kidney Mouse Diabetic Kidney Disease
350 367 Slideseq   Kidney Mouse Diabetic Kidney Disease
351 368 Slideseq   Kidney Mouse Diabetic Kidney Disease
352 369 Slideseq   Kidney Mouse Diabetic Kidney Disease
353 370 Slideseq   Kidney Mouse Diabetic Kidney Disease
354 371 Slideseq   Kidney Mouse Diabetic Kidney Disease
355 372 Slideseq   Kidney Mouse Diabetic Kidney Disease
356 373 Slideseq   Kidney Mouse Diabetic Kidney Disease
357 374 Slideseq   Kidney Mouse Diabetic Kidney Disease
358 375 Slideseq   Kidney Mouse Diabetic Kidney Disease
359 376 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
360 377 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
361 378 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
362 379 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
363 380 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
364 381 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
365 382 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
366 383 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
367 384 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
368 385 Slideseq   Kidney Mouse Autosomal Dominant Polycystic Kidney Disease
    Sample                      Number.of.Spots Number.of.Genes
1   151507                      4221            33538
2   151508                      4381            33538
3   151509                      4788            33538
4   151510                      4595            33538
5   151669                      3636            33538
6   151670                      3484            33538
7   151671                      4093            33538
8   151672                      3888            33538
9   151673                      3611            33538
10  151674                      3635            33538
11  151675                      3566            33538
12  151676                      3431            33538
13  FF3_S1_Sagittal_Posterior   3353            31053
14  FF4_S2_Sagittal_Anterior    2825            31053
15  FF5_S2_Sagittal_Posterior   3293            31053
16  FF6                         2560            31053
17  FF7                         2500            31053
18  Whole_Transcriptome         4992            36601
19  Section_Coronal             2686            32285
20  S1_Sagittal_Anterior_Level1 2693            32285
21  Block_A_Section1            3798            36601
22  Block_A_Section2            3987            36601
23  Whole_Transcriptome         4898            36601
24  sample01                    2103            36601
25  sample02                    1400            36601
26  sample03                    2364            36601
27  sample04                    2504            36601
28  sample05                    2224            36601
29  sample06                    3037            36601
30  sample07                    2086            36601
⋮   ⋮                           ⋮               ⋮
339 Puck_191109_07              21825           20550
340 Puck_191109_08              26486           19446
341 Puck_191109_09              25279           20262
342 Puck_191109_10              12465           19388
343 Puck_191112_02              17926           21286
344 Puck_191112_04              13096           20812
345 Puck_191112_05               9075           19621
346 Puck_191112_07              12675           19157
347 Puck_191112_13              14497           17669
348 Puck_191204_13              30477           22102
349 Puck_191109_14              10930           18956
350 Puck_191109_18              16582           18064
351 Puck_191109_19              16936           18447
352 Puck_191109_20              12038           17811
353 Puck_191112_08               6968           18662
354 Puck_191204_03              18868           21508
355 Puck_191204_04              20917           21855
356 Puck_191204_05              26388           21564
357 Puck_191204_07              29130           22121
358 Puck_191204_08              21518           21265
359 Puck_191223_21              21027           20803
360 Puck_191223_22              18459           21695
361 Puck_191223_23              23176           21431
362 Puck_191223_24              27116           21486
363 Puck_200102_09              24405           21651
364 Puck_200104_06              28902           21086
365 Puck_200104_07              28401           21263
366 Puck_200104_09              23887           21477
367 Puck_200104_10              24454           20322
368 Puck_200104_14              20613           20986
    Genes.Detected.per.Spot Sparsity  Avg.Expression.per.Spot
1   1409.482                0.958     0.077
2   1191.235                0.964     0.063
3   1434.161                0.957     0.076
4   1368.559                0.959     0.073
5   1796.764                0.946     0.112
6   1675.843                0.950     0.102
7   1859.503                0.945     0.116
8   1770.257                0.947     0.109
9   2207.998                0.934     0.137
10  2697.521                0.920     0.176
11  1807.521                0.946     0.107
12  1936.961                0.942     0.115
13  4541.987                0.854     0.549
14  5015.129                0.838     0.637
15  4385.757                0.859     0.506
16  4722.021                0.848     0.637
17  4389.446                0.859     0.584
18  2855.558                0.922     0.177
19  5953.154                0.816     0.988
20  5883.059                0.818     0.796
21  5621.993                0.846     0.596
22  5458.042                0.851     0.571
23  3522.717                0.904     0.280
24  2602.554                0.929     0.237
25  2337.706                0.936     0.268
26  1756.434                0.952     0.106
27  1490.822                0.959     0.088
28  2492.613                0.932     0.266
29  2348.268                0.936     0.198
30  1805.425                0.951     0.161
⋮   ⋮                       ⋮         ⋮
339 191.54515               0.9906791 0.012688714
340  84.37408               0.9956611 0.005523240
341 129.10008               0.9936285 0.008451241
342 121.45608               0.9937355 0.007990991
343 221.41459               0.9895981 0.016012911
344 187.32254               0.9909993 0.012451447
345  71.24364               0.9963690 0.005150831
346 109.90154               0.9942631 0.007933210
347  52.73801               0.9970152 0.003983201
348 270.73938               0.9877505 0.016941719
349 102.65343               0.9945846 0.008096117
350  61.87330               0.9965748 0.004977034
351  62.17932               0.9966293 0.004400163
352  58.60375               0.9967097 0.004765029
353  80.60706               0.9956807 0.005086290
354 349.74237               0.9837390 0.025502034
355 326.95788               0.9850397 0.022873504
356 293.68770               0.9863806 0.019791855
357 234.97055               0.9893779 0.015222518
358 193.42722               0.9909040 0.012158376
359 391.78499               0.9811669 0.029463859
360 436.45750               0.9798821 0.028967535
361 343.66422               0.9839642 0.023433484
362 306.32896               0.9857429 0.020359026
363 413.17959               0.9809164 0.026858885
364 296.76351               0.9859260 0.019267663
365 286.55248               0.9865234 0.019271897
366 390.69326               0.9818088 0.026945865
367 173.13654               0.9914803 0.010847545
368 352.71130               0.9831930 0.024484957
    Avg.Non.Zero.Expression.per.Spot Number.of.Clusters Annotation_Level
1   1.782                             7                 domain
2   1.723                             7                 domain
3   1.718                             7                 domain
4   1.735                             7                 domain
5   2.009                             5                 domain
6   1.965                             5                 domain
7   1.998                             5                 domain
8   1.975                             5                 domain
9   1.983                             7                 domain
10  2.094                             7                 domain
11  1.895                             7                 domain
12  1.922                             7                 domain
13  3.438                            17                 domain
14  3.770                            18                 domain
15  3.311                            18                 domain
16  3.933                            17                 domain
17  3.933                            17                 domain
18  2.069                             8                 domain
19  5.085                            15                 domain
20  4.141                             9                 domain
21  3.463                            20                 domain
22  3.463                            10                 domain
23  2.678                             9                 domain
24  2.548                             9                 domain
25  2.638                             9                 domain
26  1.932                             9                 domain
27  1.705                             9                 domain
28  3.025                             9                 domain
29  2.404                             9                 domain
30  2.387                             9                 domain
⋮   ⋮                                ⋮                  ⋮
339 1.291849                         14                 celltype
340 1.216153                         13                 celltype
341 1.252716                         14                 celltype
342 1.216045                         13                 celltype
343 1.396501                         14                 celltype
344 1.286999                          9                 celltype
345 1.304500                         12                 celltype
346 1.291995                         13                 celltype
347 1.231522                         11                 celltype
348 1.253705                         14                 celltype
349 1.428996                         12                 celltype
350 1.422188                         13                 celltype
351 1.241214                         13                 celltype
352 1.430274                         13                 celltype
353 1.130741                         12                 celltype
354 1.374383                         14                 celltype
355 1.360675                         14                 celltype
356 1.314982                         14                 celltype
357 1.300891                         14                 celltype
358 1.231232                         14                 celltype
359 1.407635                         14                 celltype
360 1.304167                         10                 celltype
361 1.308914                         14                 celltype
362 1.296865                         14                 celltype
363 1.262877                         10                 celltype
364 1.258529                         12                 celltype
365 1.297987                         12                 celltype
366 1.322177                         13                 celltype
367 1.191887                         13                 celltype
368 1.299718                         10                 celltype
    Original_Annotation                    Level
1   Manual Annotation                      Level 1
2   Manual Annotation                      Level 1
3   Manual Annotation                      Level 1
4   Manual Annotation                      Level 1
5   Manual Annotation                      Level 1
6   Manual Annotation                      Level 1
7   Manual Annotation                      Level 1
8   Manual Annotation                      Level 1
9   Manual Annotation                      Level 1
10  Manual Annotation                      Level 1
11  Manual Annotation                      Level 1
12  Manual Annotation                      Level 1
13  Unsupervised clustering                Level 3
14  Unsupervised clustering                Level 3
15  Unsupervised clustering                Level 3
16  Unsupervised clustering                Level 3
17  Unsupervised clustering                Level 3
18  Unsupervised clustering                Level 3
19  Manual Annotation                      Level 1
20  Manual Annotation                      Level 1
21  Manual Annotation                      Level 1
22  Unsupervised clustering                Level 3
23  Unsupervised clustering                Level 3
24  Unsupervised clustering + Marker genes Level 1
25  Unsupervised clustering + Marker genes Level 1
26  Unsupervised clustering + Marker genes Level 1
27  Unsupervised clustering + Marker genes Level 1
28  Unsupervised clustering + Marker genes Level 1
29  Unsupervised clustering + Marker genes Level 1
30  Unsupervised clustering + Marker genes Level 1
⋮   ⋮                                      ⋮
339 Supervised Transfer                    Level 2
340 Supervised Transfer                    Level 2
341 Supervised Transfer                    Level 2
342 Supervised Transfer                    Level 2
343 Supervised Transfer                    Level 2
344 Supervised Transfer                    Level 2
345 Supervised Transfer                    Level 2
346 Supervised Transfer                    Level 2
347 Supervised Transfer                    Level 2
348 Supervised Transfer                    Level 2
349 Supervised Transfer                    Level 2
350 Supervised Transfer                    Level 2
351 Supervised Transfer                    Level 2
352 Supervised Transfer                    Level 2
353 Supervised Transfer                    Level 2
354 Supervised Transfer                    Level 2
355 Supervised Transfer                    Level 2
356 Supervised Transfer                    Level 2
357 Supervised Transfer                    Level 2
358 Supervised Transfer                    Level 2
359 Supervised Transfer                    Level 2
360 Supervised Transfer                    Level 2
361 Supervised Transfer                    Level 2
362 Supervised Transfer                    Level 2
363 Supervised Transfer                    Level 2
364 Supervised Transfer                    Level 2
365 Supervised Transfer                    Level 2
366 Supervised Transfer                    Level 2
367 Supervised Transfer                    Level 2
368 Supervised Transfer                    Level 2

In [13]:
df_all <- df_meta
technology_order <- c('ST', '10x Visium', 'Slideseq', 'Stereoseq', 'VisiumHD', 
                      'seqFISH', 'STARmap', 'MERFISH', 'CosMx', 'Xenium')

technology_colors <- c(
  'ST' = '#FF7F0E',
  '10x Visium' = '#1F77B4', 
  'Slideseq' = '#2CA02C',
  'Stereoseq' = '#9467BD',
  'VisiumHD' = '#D62728',
  'seqFISH' = '#8C564B',
  'STARmap' = '#E377C2',
  'MERFISH' = '#7F7F7F',
  'CosMx' = '#BCBD22',
  'Xenium' = '#17BECF'
)

df_all$Technology <- factor(df_all$Technology, levels = technology_order)

summary_stats <- function(data, metric) {
  data %>%
    group_by(Technology) %>%
    summarise(
      mean_val = mean(.data[[metric]], na.rm = TRUE),
      sd_val = sd(.data[[metric]], na.rm = TRUE)
    )
}

plot_metric <- function(data, metric, xlabel, digits = 0, log_scale = FALSE) {
  stats <- summary_stats(data, metric)
  stats$Technology <- factor(stats$Technology, levels = rev(technology_order))
  if (digits == 0) {
    stats$label <- sprintf("%d", round(stats$mean_val))
  } else {
    stats$label <- sprintf(paste0("%.", digits, "f"), stats$mean_val)
  }
  
  p <- ggplot(stats, aes(x = mean_val, y = Technology, fill = Technology)) +
    geom_col(color = "black", width = 0.6) +
    geom_errorbarh(aes(xmin = mean_val - sd_val, xmax = mean_val + sd_val),
                   height = 0.3, size = 0.5, color = "black") +
    geom_text(aes(label = label), hjust = -0.1, size = 3) +
    scale_fill_manual(values = technology_colors) +
    labs(x = xlabel, y = NULL) +
    theme_minimal(base_size = 8) +
    theme(
      legend.position = "none",
      axis.text.y = element_text(size = 7),
      axis.text.x = element_text(size = 7),
      axis.title.x = element_text(size = 8),
      panel.grid.major.y = element_blank(),
      panel.grid.minor = element_blank()
    )
  
  if (log_scale) {
    p <- p + scale_x_log10() + annotation_logticks(sides = "b")
  }
  
  return(p)
}


p1 <- plot_metric(df_all, "Number.of.Spots", "Number of Spots", digits = 0, log_scale = TRUE)
p2 <- plot_metric(df_all, "Number.of.Genes", "Number of Genes", digits = 0, log_scale = TRUE)
p3 <- plot_metric(df_all, "Sparsity", "Sparsity", digits = 3, log_scale = FALSE)
pdf("plot_metrics.pdf", width = 18 / 2.54, height = 6 / 2.54)
grid.arrange(p1, p2, p3, ncol = 3)
dev.off()

png
  2